### PR TITLE
Migrate magentoerpconnect_pricing

### PR DESCRIPTION
**Pull request by guewen**

### CODE REVIEW

**Comment by thomich** [comment]
updated now my local buildout and wanted to install magenoterpconnect_pricing, but got this error:
AttributeError: 'int' object has no attribute 'id'
details: http://paste.ubuntu.com/10950593/

**Comment by guewen** [comment]
> updated now my local buildout and wanted to install magenoterpconnect_pricing, but got this error:
> AttributeError: 'int' object has no attribute 'id'
> details: http://paste.ubuntu.com/10950593/

I guess it is this one: https://github.com/OCA/e-commerce/pull/44

**Comment by guewen** [comment]
@thomich OCA/e-commerce#44 has been merged, could you update your branches and retry?

**Comment by thomich** [comment]
@guewen i try to, but get error on ./bin/buildout:
fatal: Not possible to fast-forward, aborting.
...
UpdateError: Command '['git', 'merge', '--ff-only', 'FETCH_HEAD']' returned non-zero exit status 128

details: http://paste.ubuntu.com/10951385/

**Comment by guewen** [comment]
@thomich you have to update or reset the branch manually in parts/e-commerce. if you didn't modify anything in the branch and don't mind to delete it, you can also rm -rf parts/e-commerce and run again bin/buildout.

**Comment by thomich** [comment]
done... thanks @guewen 
will update soon with more information or questions ;) on comm.list

**Comment by guewen** [comment]
Rebased on #85

**Comment by guewen** [comment]
Rebased on top of the head after 3.0.0

**Comment by thomich** [comment]
is it possible to merge this PR in this days?

**Comment by thomich** [comment]
Deprecated call to install_in_connector()
File/Line: connector.py / 25

WARNING dbname openerp.addons.magentoerpconnect_pricing.connector: Deprecated: <module> at line 25: This call to 'install_in_connector()' has no effect and is not required.

**Comment by thomich** [comment]
about build error:  ImportError: No module named magento

we need py lib magento:
sudo easy_install magento

**Comment by lmignon** [comment]
@guewen I've rebased your branch on oca/8.0 at e33ef6bc9da90587bb85ff6f61d33c013e0f5567
Feel free to push my branch https://github.com/acsone/connector-magento/tree/8.0-magentoerpconnect_pricing-migr-lmi on yours.

**Comment by guewen** [comment]
@lmignon thanks, done (had to do another rebase though)

**Comment by guewen** [comment]
Once green if nobody disagree, I will merge, since the time...

**Pull request merged**
