### PR TITLE
Use False instead of None in ol_catalog_product parameters

### PR DESCRIPTION
**Pull request by mdietrichc2c**
This PR is to fix an issue I had with Magento 1.14 (Enterprise Edition): if the methods on `ol_catalog_product` are called using `None` for the optional parameters, the call fails.

Ex: 

```
m.call('ol_catalog_product.info', ['19030', None, None, 'id'])
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/mdietrich/nobackup/projects/debonix_openerp/eggs/magento-0.4-py2.7.egg/magento/api.py", line 161, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 794, in close
    raise Fault(**self._stack[0])
Fault: <Fault 636: 'Error creating xmlrpc value'>
```

However, using `False` or `0` instead, the call now works fine. It is also the case for version 1.7, so this fix is backwards-compatible.

### CODE REVIEW

**Comment by guewen** [comment]
:+1:

**Comment by mdietrichc2c** [comment]
I needed to modify the dictionary for test messages accordingly.

**Comment by mdietrichc2c** [comment]
Last issue found (still a `storeview_id=False` remaining)

**Comment by StefanRijnhart** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
