### PR TITLE
8.0 magento2

### PR DESCRIPTION
**Pull request by vimalvkg**

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
I think this branch needs some more work, and we're still waiting for the merge on the fulfilio lib. If you want to help, please consider fixing and adding tests.

**Comment by IJOL** [comment]
JUst found that and badly needing it, so i will help, but tests and that s*** are not for me, anyway in your ( i assume )  expert position, where is that help needed? and sorry for be so late, just 9 days after you give up, is this heaven sign? ;)

**Comment by thomaspaulb** [comment]
@StefanRijnhart When something is not finished, it at least needs some place where the code can be discussed, that is why normally a [WIP] pull request is opened. Is there any reason why you don't do this and others do?

For example now, there is a merge conflict.

**Comment by StefanRijnhart** [comment]
@thomaspaulb I guess that's another way of looking at it. I'll open my own pull request if you think that will help.

**Comment by StefanRijnhart** [comment]
Here you go: https://github.com/OCA/connector-magento/pull/289. Will have a look at the conflict later.

**Pull request closed without merging**
