### PR TITLE
[WIP][DRAFT][MIG][13.0] connector magento

### PR DESCRIPTION
**Pull request by bizzappdev**

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
@bizzappdev this is not looking bad at all! Any chance you are going to finish the work?

**Comment by PCatinean** [comment]
@StefanRijnhart we are already using this for developing a few projects. Let us know what needs changing / working on and we'll get to it.

**Comment by paulius-sladkevicius** [comment]
I can confirm that we're using it too and have had some minor issues that we plan to contribute in near feature.

**Comment by StefanRijnhart** [comment]
Great! I think it's just CI that needs to be fixed and the minor issues that you have encountered.

**Comment by bizzappdev** [comment]
This weekend I will try to clear CI issues

**Comment by paulius-sladkevicius** [comment]
@PCatinean @bizzappdev to be sure, is this one based on https://github.com/OCA/connector-ecommerce/pull/53?
FYI, we'll create PR soon with our fixes.

**Comment by bizzappdev** [comment]
> @PCatinean @bizzappdev to be sure, is this one based on [OCA/connector-ecommerce#53](https://github.com/OCA/connector-ecommerce/pull/53)?
> FYI, we'll create PR soon with our fixes.
Yes, this was based on that only.
There is one Fix needs to be added for Sale order Onchange.
I have already fix for that not sure it is proper or not. 
https://github.com/bizzappdev/connector-ecommerce/commit/7f73f7c393c23f3d5b70ef5a0cc18e6df8799dbe
https://github.com/bizzappdev/connector-ecommerce/commit/48d1ef16a515fa5947a1420e970f1c8186084a10
other than that we did not had any major issues

**Comment by paulius-sladkevicius** [comment]
@bizzappdev any chance to take the lead and make/finish PR of OCA/connector-ecommerce#53 as existing person stopped to continue on it?

**Comment by bizzappdev** [comment]
IMO only functional test needs to be done on that PR.
If we have list of issues to be fixed then I can proceed for proper Fix.
as in our normal functional test I was only able to find those 2 issues.
PR created https://github.com/OCA/connector-ecommerce/pull/59.
feel free to do functional review.
I will also take care for CI things once it is ready

**Comment by StefanRijnhart** [comment]
Thanks @bizzappdev. BTW there have been some fixes on the 12.0 branch: https://github.com/OCA/connector-magento/commits/12.0. Can you pick the relevant commits or rebase your changes on a new 'format-patch' of the 12.0 branch?

**Comment by bizzappdev** [comment]
@StefanRijnhart sure will do the needful.

**Comment by bizzappdev** [comment]
Not sure why it gets closed I just rebased on 12.0.  can anyone reopen again? or I have to create another PR.

**Comment by StefanRijnhart** [comment]
You rebased on 12.0 instead of on what I called, for lack of a better word, a new 'format-patch' of this module in 12.0 (with which I tried to refer to this process: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#technical-method-to-migrate-a-module-from-120-to-130-branch). So now, the branch histories of your branch and 13.0 are not related anymore as indicated when trying to open a new PR: 
image

**Comment by bizzappdev** [comment]
New PR created #317 
Sorry for the mess up.

**Comment by StefanRijnhart** [comment]
Did you try force pushing your branch so that we can continue on this PR?

**Comment by bizzappdev** [comment]
I tried but it is not working that way so created new PR

**Comment by StefanRijnhart** [comment]
Ah ok, thanks!

**Pull request closed without merging**
