### PR TITLE
Port server_env_magentoerpconnect

### PR DESCRIPTION
**Pull request by nbessi**

### CODE REVIEW

**Comment by nbessi** [comment]
@gurneyalex can you have a look on the runbot please

**Comment by gurneyalex** [comment]
merging #128 and rebasing this PR should make runbot happy.

**Comment by nbessi** [comment]
@gurneyalex thanks

**Comment by atchuthan** [comment]
@nbessi we could close this PR as the code is merged in https://github.com/OCA/connector-magento/pull/199

**Comment by guewen** [comment]
thanks for the notice @atchuthan, closed

**Pull request closed without merging**
