### PR TITLE
typo on field used in ecommerce to manage giftcode

### PR DESCRIPTION
**Pull request by damdam-s**
to be coherent with https://github.com/OCA/connector-ecommerce/blob/8.0/connector_ecommerce/sale.py#L322-L323

### CODE REVIEW

**Comment by guewen** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
:+1:, thanks!

**Comment by damdam-s** [comment]
up ! 
I added a control to avoid creating SO line with `amount  = 0` if no gift is in the magento order.

**Comment by atchuthan** [comment]
:+1:

**Pull request merged**
