### PR TITLE
8.0 wrap synchronize (trust-code)

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Adopted https://github.com/OCA/connector-magento/pull/133 by @danimaribeiro

**Comment by StefanRijnhart** [comment]
:+1: as I am not the original author

**Comment by guewen** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by atchuthan** [comment]
:+1:

**Pull request merged**
