### PR TITLE
[IMP] Changes in total_amount and create payment when the store currecy ...

### PR DESCRIPTION
**Pull request by albertofl**
[IMP] Changes in total_amount and create payment when the store currecy is different to sale order currency

### CODE REVIEW

**Comment by guewen** [comment]
Can you rebase please?

**Comment by OSguard** [comment]
i think this change is incomplete and needs test.

I miss the handling of SaleOrderLineImportMapper including discount. I think only handling total will not cover all case and there will be need for some addational work.
As well it only will work if the base currency in magento is the same as in OpenERP. So we need a additional description.

But i m not a export on multi currency setup.

**Comment by pedrobaeza** [comment]
@liebana, are you going to work on this?

**Comment by pedrobaeza** [comment]
As there's no answer, I close. Feel free to reopen in case there's interest.

**Pull request closed without merging**
