### PR TITLE
beautifulsoup with more vegetables

### LINKED ISSUE #34: magentoerpconnect_order_comment: nltk.clean_html() raises a NotImplementedError
magentoerpconnect_order_comment uses `nltk.clean_html(comment)` which does no longer work. It has been removed from the lib in version 3.0: https://github.com/nltk/nltk/commit/39a303e5ddc4cdb1a0b00a3be426239b1c24c8bb

From Travis:

```
2014-09-10 10:23:45,300 23456 TEST openerp_test openerp.modules.module: ERROR: test_20_export_sale_comment (openerp.addons.magentoerpconnect_order_comment.tests.test_synchronization.TestMagentoSaleCommentExport)

2014-09-10 10:23:45,300 23456 TEST openerp_test openerp.modules.module: ` Test export of sale order comment

2014-09-10 10:23:45,300 23456 TEST openerp_test openerp.modules.module: Traceback (most recent call last):

2014-09-10 10:23:45,300 23456 TEST openerp_test openerp.modules.module: ` File "/home/travis/build/OCA/connector-magento/magentoerpconnect_order_comment/tests/test_synchronization.py", line 154, in test_20_export_sale_comment

2014-09-10 10:23:45,300 23456 TEST openerp_test openerp.modules.module: ` export_record(self.session, 'magento.sale.comment', mag_comment_id)

2014-09-10 10:23:45,300 23456 TEST openerp_test openerp.modules.module: ` File "/home/travis/build/OCA/connector-magento/magentoerpconnect/unit/export_synchronizer.py", line 389, in export_record

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` return exporter.run(binding_id, fields=fields)

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` File "/home/travis/build/OCA/connector-magento/magentoerpconnect/unit/export_synchronizer.py", line 124, in run

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` result = self._run(*args, **kwargs)

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` File "/home/travis/build/OCA/connector-magento/magentoerpconnect/unit/export_synchronizer.py", line 375, in _run

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` record = self._create_data(map_record, fields=fields)

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` File "/home/travis/build/OCA/connector-magento/magentoerpconnect/unit/export_synchronizer.py", line 330, in _create_data

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` return map_record.values(for_create=True, fields=fields, **kwargs)

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` File "/home/travis/connector/connector/unit/mapper.py", line 904, in values

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` values = self._mapper._apply(self, options=options)

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` File "/home/travis/connector/connector/unit/mapper.py", line 643, in _apply

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` return self._apply_with_options(map_record)

2014-09-10 10:23:45,301 23456 TEST openerp_test openerp.modules.module: ` File "/home/travis/connector/connector/unit/mapper.py", line 681, in _apply_with_options

2014-09-10 10:23:45,302 23456 TEST openerp_test openerp.modules.module: ` values = meth(map_record.source)

2014-09-10 10:23:45,302 23456 TEST openerp_test openerp.modules.module: ` File "/home/travis/build/OCA/connector-magento/magentoerpconnect_order_comment/sale.py", line 282, in comment

2014-09-10 10:23:45,302 23456 TEST openerp_test openerp.modules.module: ` return {'comment': nltk.clean_html(comment)}

2014-09-10 10:23:45,302 23456 TEST openerp_test openerp.modules.module: ` File "/usr/local/lib/python2.7/dist-packages/nltk/util.py", line 346, in clean_html

2014-09-10 10:23:45,302 23456 TEST openerp_test openerp.modules.module: ` raise NotImplementedError ("To remove HTML markup, use BeautifulSoup's get_text() function")

2014-09-10 10:23:45,302 23456 TEST openerp_test openerp.modules.module: ` NotImplementedError: To remove HTML markup, use BeautifulSoup's get_text() function
```

It should be replaced by BeautifulSoup or another library / own function that does the same thing.
Maybe we have to freeze the version of `nltk`, but it will be a problem some day.

### PR DESCRIPTION
**Pull request by guewen**
nltk does no longer have a `clean_html` function. It should be done with beautifulsoup4.

Fixes #34

### CODE REVIEW

**Comment by guewen** [comment]
@bealdav Travis got green, can you review?

**Comment by guewen** [comment]
BTW I :+1: (I'm not the author, just fixed @bealdav issues with travis and dependencies)

**Comment by nbessi** [comment]
:+1:

**Comment by bealdav** [comment]
:+1:

**Comment by bealdav** [comment]
@guewen thank you to find the solution
for my personal info, you know why:
sudo pip install beautifulsoup4
'python': ['bs4'],

thanks

**Comment by guewen** [comment]
@bealdav you choose a name for the build package (distributed as egg on pypi for instance), but you may have a different name for the python package **inside** your egg (or even have several of them).
Example: the name in this setup.py http://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/view/head:/setup.py is beautifulsoup4, but it contains 3 python packages: 'bs4', 'bs4.builder', 'bs4.tests', see http://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/files

**Comment by bealdav** [comment]
thanks a lot :100:

**Pull request merged**
