### PR TITLE
[8.0] add missing ACL to allow warehouse user to deliver an order

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by guewen** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by guewen** [comment]
ouch, tests failing due to missing periods :-( : `There is no period defined for this date: 2016-01-31`. (unrelated)

**Comment by Cedric-Pigeon** [comment]
@pedrobaeza Thanks, I think it can be merged.

**Comment by pedrobaeza** [comment]
Merging, but tests should be done multi-year aware in other PR

**Pull request merged**
