### PR TITLE
Setup transifex

### PR DESCRIPTION
**Pull request by guewen**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Change coveralls

**Comment by pedrobaeza** [comment]
Runbot is failing because magento lib is not installed. As @gurneyalex is on holidays, someone with SSH access to the runbot host must install it

**Comment by guewen** [comment]
@pedrobaeza I was about to change it, you was faster than me ;-)

Done the changes

**Comment by pedrobaeza** [comment]
:+1:

**Comment by max3903** [comment]
:+1: 

I just installed magento lib on runbots

**Comment by guewen** [comment]
Thanks @max3903 
I restarted the runbot build

**Comment by guewen** [comment]
Runbot says `ImportError: No module named connector_ecommerce`
Did I miss something with the dependencies?

**Comment by pedrobaeza** [comment]
connector-ecommerce is put as dependency, so it should work. I have restarted again to see.

**Comment by pedrobaeza** [comment]
The error is because you are using `from openerp.addons.connector_ecommerce.unit.sale_order_onchange import...` expression, which maybe on the runbot architecture cannot be resolved due to python paths and so on, but I don't know enough the internals of runbot to know it.

**Comment by guewen** [comment]
> The error is because you are using from openerp.addons.connector_ecommerce.unit.sale_order_onchange import... expression, which maybe on the runbot architecture cannot be resolved due to python paths and so on, but I don't know enough the internals of runbot to know it.

This import is correct though.

**Pull request merged**
