### PR TITLE
Remove trailing None on calls made to the Magento's API (PHP 5.4 compatibility)

### PR DESCRIPTION
**Pull request by guewen**
When Magento is used with PHP 5.4+, the API may return errors if we send
API calls with None in the last arguments. So, we remove all the trailing
None from the arguments before sending.

### CODE REVIEW

**Comment by guewen** [comment]
Superseed https://github.com/OCA/connector-magento/pull/19

**Comment by yvaucher** [comment]
@guewen To be rebased

**Comment by guewen** [comment]
Rebased

**Comment by gurneyalex** [comment]
:+1:

**Comment by nbessi** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
