### PR TITLE
Automatically build Sphinx documentation

### PR DESCRIPTION
**Pull request by guewen**
Once merged, Travis will automatically build the documentation on the branch `8.0` on every commit and push it on odoo-magento-connector.com

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1:

**Comment by guewen** [comment]
Runbot is red (on all the connector-magento PR in fact) but Travis is green

**Comment by mdietrichc2c** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Pull request merged**
