### PR TITLE
migration of magentoerpconnect_export_partner

### PR DESCRIPTION
**Pull request by guewen**
Merge only after #85
The full diff of #85 + this one is presented here.

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Needs a rebase, I'm afraid

**Comment by StefanRijnhart** [comment]
Otherwise, :+1:

**Comment by simahawk** [comment]
@guewen #85 is merged and code looks fine except the missing rebase ;)

**Comment by simahawk** [comment]
BTW [the build](https://runbot.odoo-community.org/runbot/build/3110206) is failing with 

```
ImportError: No module named magento
```

sounds like a missing dependency...

**Comment by pedrobaeza** [comment]
This one conflicts, so for sure there's another PR merging this. If not and this is still useful, please reopen.

**Pull request closed without merging**
