### PR TITLE
Add base files for the branch (.travis.yml, .coveragerc, .gitignore, README.md, LICENSE)

### PR DESCRIPTION
**Pull request by guewen**

### CODE REVIEW

**Comment by bwrsandman** [comment]
Pep8 error can be solved later, but the following suggests there are some pip dependencies missing:

```
except_orm: ('Error', u'Unable to install module "magentoerpconnect" because an external dependency is not met: No module named magento')
```

**Comment by guewen** [comment]
Yes, I am going to fix that.

**Comment by guewen** [comment]
`server_env_magentoerpconnect` depends on `server_environment` and as far as I know, this module makes fail the tests because it needs an special option to be defined :angry:

**Comment by guewen** [comment]
```
('Error', u'Unable to install module "magentoerpconnect" because an external dependency is not met: No module named magento')
```

I added `pip install magento` in the file though, any idea?

**Comment by pedrobaeza** [comment]
Well, I have no clue. Maybe a question of virtualenv?

**Comment by guewen** [comment]
Flake8 fixes are here: https://github.com/OCA/connector-magento/pull/8

**Comment by guewen** [comment]
@bwrsandman do you have an idea why it still raises `except_orm: ('Error', u'Unable to install module "magentoerpconnect" because an external dependency is not met: No module named magento')`?

Also, I'm blocked by the module `server_env_magentoerpconnect` because it needs a `running_env` in the odoo's config file. Also, I think it has the potential to break other tests because it replace the location, username and password of the magento backends by fields.function that reads the values in configuration files instead of the database. Could we blacklist modules such as this one?

**Comment by bwrsandman** [comment]
I have no idea why it says that but I know how to solve the problem: use `sudo pip install magento`

**Comment by guewen** [comment]
Nice, thanks @bwrsandman 

Now, only the issue with `server_env_magentoerpconnect` lasts.

**Comment by guewen** [comment]
Tests are passing! Still failed due to the pep8, that is corrected here: https://github.com/OCA/connector-magento/pull/8
So I will deactivate the pep8 checks here and reactivate them in the pep8 branch.

**Comment by gurneyalex** [comment]
LGTM :+1:

**Comment by bwrsandman** [comment]
:+1:

**Pull request merged**
