### PR TITLE
Fix flake8 warning, operator after line break

### PR DESCRIPTION
**Pull request by guewen**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by guewen** [comment]
But now the link check fails with `ImportError: No module named lxml` :confused:

**Comment by pedrobaeza** [comment]
Uhm, strange. It seems a Travis bug

**Comment by lmignon** [comment]
:+1:  For sure, the failure doesn't come from your changes

**Comment by StefanRijnhart** [comment]
I restarted travis and it's green now. :+1:

**Pull request merged**
