### PR TITLE
Refactor code in order to be compatible with fiscal position rule module

### PR DESCRIPTION
**Pull request by sebastienbeau**
Partner and address must be set correctly before calling the onchange method.
With this refactor and this other PR https://github.com/OCA/connector-ecommerce/pull/7, the fiscal position are set correctly on sale order when importing a sale order

### CODE REVIEW

**Comment by guewen** [comment]
I was sure it was already working, anyway the code is better know I think, using the options of the mapper.

Thanks

:+1:

**Comment by sebastienbeau** [comment]
A case that was not working was the case where you create a customer with a Suisse address as main address and send the delivery to France.
In this case the address used for setting the fiscal position will be the suisse one and not the french one (In France fiscal position are based on delivery address).

**Comment by bguillot** [comment]
Thanks

:+1:

**Comment by florian-dacosta** [comment]
:+1:

**Pull request merged**
