### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by maxime-c2c**

### CODE REVIEW

**Comment by guewen** [comment]
Thanks :+1:

**Comment by yvaucher** [comment]
:tada: :+1:

**Comment by damdam-s** [comment]
:+1: :confetti_ball:

**Comment by gurneyalex** [comment]
e-CLA for Maxime via Camptocamp. I'll update the clabot database.

**Comment by elicoidal** [comment]
I already created the user in the ERP (miss his last name though)
Eric CAUDAL

**Pull request closed without merging**
