### PR TITLE
[FIX] replace 'nltk' use by bs4

### PR DESCRIPTION
**Pull request by bealdav**
Fixed this bug
https://github.com/OCA/connector-magento/issues/34#issuecomment-55110154

Thanks for the review

### CODE REVIEW

**Comment by bealdav** [comment]
_

**Comment by guewen** [comment]
@bealdav you have to add `sudo pip install beautiful4` in `.travis.cfg`

**Comment by bealdav** [comment]
@guewen 
travis tells ('Error', u'Unable to install module "magentoerpconnect_order_comment" because an external dependency is not met: No module named beautifulsoup4')
whereas i put 'sudo pip install beautifulsoup4' in .travis.yml 
? what can I do ?
.travis.cfg is ...yml, ok

**Comment by guewen** [comment]
Could it be an error with the casing (beautifulsoup4, Beautifulsoup4)?

**Comment by bealdav** [comment]
It also failed at this step
https://github.com/bealdav/connector-magento/commit/2394c90cff21b9e5dfccff94fbe168663cb9e42c

and pip command works in local

**Comment by guewen** [comment]
From my tests, it should be 'bs4'. Maybe it is installed as a zip... I know that openerp does not detect the eggs installed as zip (it uses imp.find_module())

**Comment by bealdav** [comment]
Caramba encore raté.
It failed with bs4 in yml and _oe_.py.
Damned ;-)

**Comment by guewen** [comment]
Superseeded by https://github.com/OCA/connector-magento/pull/40

**Pull request closed without merging**
