### PR TITLE
completed and improved german translations

### PR DESCRIPTION
**Pull request by rschnapka**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by guewen** [comment]
Thanks! :+1: (but I can't review German ;-)

**Comment by yvaucher** [comment]
:+1: Half reviewed German (can't do better)
I think we can merge this

Thanks

**Comment by yvaucher** [comment]
Fixed 2 missing `"` at end of string in https://github.com/OCA/connector-magento/pull/77

**Pull request merged**
