### PR TITLE
Prevent to create duplicate bindings on invoices

### PR DESCRIPTION
**Pull request by guewen**
The correction made at becc1bf2 was not working because it was
doing a 'continue' on the inner loop but not on the outer loop.

### CODE REVIEW

**Comment by guewen** [comment]
Travis fails because of https://github.com/OCA/connector-magento/issues/34

**Comment by nbessi** [comment]
:+1:

**Comment by guewen** [comment]
Rebased so #34 will no longer make travis fail.

**Comment by OSguard** [comment]
:+1:

**Pull request merged**
