### PR TITLE
update location of scheduler and fix wording

### PR DESCRIPTION
**Pull request by otherjustin**
The location of the scheduled actions has changed without the documentation being updated. Also fixed some small wording problems.

### CODE REVIEW

**Comment by guewen** [comment]
Thanks! :+1:

**Comment by StefanRijnhart** [comment]
Care to sign the OCA Contributor licence agreement, @otherjustin?

**Comment by atchuthan** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
@guewen I think we can merge this trivial change without the CLA. Otherwise, it has to be closed.

**Comment by guewen** [comment]
@StefanRijnhart Agree.

Thanks @otherjustin for the improvement!

**Pull request merged**
