### PR TITLE
[FIX] set correct product inside shipping line based on carrier method.

### PR DESCRIPTION
**Pull request by ghost**
Resolve of the issue #112. 

While calling of the get_line() method of class MagentoShippingLineBuilder inherited from SpecialOrderLineBuilder(inside connector_ecommerce/sale.py)  takes "product" attribute of self(object)
ref : https://github.com/OCA/connector-ecommerce/blob/8.0/connector_ecommerce/sale.py#L269
while inside code of _add_shipping_line() method "product_id" is set.
ref : https://github.com/OCA/connector-magento/blob/8.0/magentoerpconnect/sale.py#L468

### CODE REVIEW

**Comment by guewen** [comment]
Did you sign the CLA?
Could you keep my commit ownership on the test? (it means that you should remove your commit and cherry-pick mine from my branch)

**Comment by ghost** [comment]
What I need to do for sign CLA ?
can you help me on that ?

**Comment by ghost** [comment]
"Could you keep my commit ownership on the test? (it means that you should remove your commit and cherry-pick mine from my branch)"

What I need to do to follow ? can you explain more ?
thanks  :)

**Comment by guewen** [comment]
Here is the OCA page on the CLA: https://odoo-community.org/page/cla

For the ownership of the commit, on your branch, do:

```
git reset --hard HEAD^
git remote add guewen git@github.com:guewen/connector-magento
git fetch guewen
git cherry-pick 290d05c5387ae2fa1b4b75b42cc004aee431760a
git push -f
```

**Comment by ghost** [comment]
on command : git fetch guewen
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by guewen** [comment]
You need to configure a ssh key on github and on your computer.
Anyway, you can use this remote url instead: `git remote add guewen https://github.com/guewen/connector-magento.git`

**Comment by guewen** [comment]
Oops, I forgot `.git` on `git remote add guewen git@github.com:guewen/connector-magento.git`

**Comment by ghost** [comment]
I have done as you have guide. But still runbot test is fail. Please have a look on it.

**Comment by guewen** [comment]
Thanks for the change! Ignore the runbot build. Did you sign the CLA too?

**Comment by ghost** [comment]
May I know some basic information ?
What is the benefit to sign the CLA ?
If I will be a member / contributor then what is the benefit of it ?
your reply would be grateful to us.
Thanks.

**Comment by guewen** [comment]
The OCA requests every contributor to sign the CLA. You have some information on https://odoo-community.org/page/cla 

I you need more information, please send an email at cla@odoo-community.org

**Comment by guewen** [comment]
@emiprotechnologies could you ask the information you want and eventually sign the CLA? Can we move forward with this PR?

**Comment by ghost** [comment]
I will sign the CLA and send it to the OCA.

**Comment by ghost** [comment]
I have sent an email with CLA document. Can you have a look on it ?
Thanks.

**Comment by guewen** [comment]
CLA Ok. Thanks!

:+1: for the merge

**Comment by pedrobaeza** [comment]
:+1:

**Comment by ghost** [comment]
Hi @guewen ,

I got an account for the OCA. But I can not set my github account from user => preferences.

Can you help me out for this ?

I want to contribute inside some repo of OCA.

Thanks for your support.
Regards.

**Pull request merged**
