### PR TITLE
[12.0][RFR] Refactor to savepointcase where possible

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Anecdotal evidence of speed increase:
This PR:
image
Other PR that I just updated:
image

**Review by pedrobaeza — APPROVED** [review]

**Review by astirpe — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
I will attempt a rebase and check any remaining errors.

**Comment by StefanRijnhart** [comment]
CI is fixed now. I suspect it was green  initially because https://github.com/OCA/connector/commit/f83d044f0daab1fc09bd91642eacf57c02c4f712 was not there yet at the time. With this in place I could, and had to, remove the remaining setUp code to the test's setUpClass method.

**Pull request merged**
