### PR TITLE
Add/12.0/magento2

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Contains all of https://github.com/OCA/connector-magento/pull/292 until that one is merged

**Review by MPishpecki — APPROVED** [review]
Tested the configuration sync and order import. Magento 2.3.5 specifically.

**Review by PhilippeBach — APPROVED** [review]
Using this version in production since one month with odoo 12 and magento 2.3.4 
very good job

**Comment by StefanRijnhart** [comment]
@PhilippeBach thanks for your feedback here but especially for reporting the bugs when I was still working on this!

**Comment by pedrobaeza** [comment]
Should we merge this?

**Comment by pedrobaeza** [comment]
(some commit squashing seems to be needed before)

**Comment by StefanRijnhart** [comment]
If we accept this as superseding https://github.com/OCA/connector-magento/pull/292 (which it includes), then I can do some squashing.

**Comment by StefanRijnhart** [comment]
@pedrobaeza I rebased but I guess it's a bit subjective which commits from the same authors to keep and which to squash so I hope it's ok.

**Comment by pedrobaeza** [comment]
Yes, just a bit as you have done is enough, thanks

/ocabot merge nobump

**Pull request merged**
